create database QLBH
go
use QLBH
CREATE TABLE KHACHHANG(
MAKH CHAR (50) NOT NULL,
HOTEN VARCHAR (50) not null,
DCHI VARCHAR (50) not null,
SODT VARCHAR (50) not null,
NGSINH SMALLDATETIME ,
NGDK SMALLDATETIME ,
DOANHSO MONEY NOT NULL 
)
ALTER TABLE KHACHHANG
ADD 
CONSTRAINT pk_KHACHHANG PRIMARY KEY ( MAKH )
GO

CREATE TABLE NHANVIEN(
MANV CHAR (50) NOT NULL,
HOTEN VARCHAR (50) not null,
NGVL SMALLDATETIME,
SODT VARCHAR (50) not null 
)
ALTER TABLE NHANVIEN
ADD 
CONSTRAINT pk_NHANVIEN PRIMARY KEY ( MANV )
GO 

CREATE TABLE SANPHAM(
MASP CHAR (50) NOT NULL,
TENSP VARCHAR (50) not null,
DVT VARCHAR (50) not null,
NUOCSX VARCHAR (50) not null,
GIA MONEY  NOT NULL 
)
ALTER TABLE SANPHAM
ADD 
CONSTRAINT pk_SANPHAM PRIMARY KEY (MASP )
GO

CREATE TABLE HOADON(
SOHD CHAR (50) NOT NULL,
NGHD SMALLDATETIME not null,
MAKH CHAR (50) not null,
MANV CHAR (50) not null,
TRIGIA MONEY 
)
ALTER TABLE HOADON
ADD 
CONSTRAINT pk_HOADON PRIMARY KEY ( SOHD )
GO

CREATE TABLE CTHD(
SOHD CHAR (50) NOT NULL,
MASP CHAR (50) not null,
SL VARCHAR (50) not null
)
ALTER TABLE CTHD
ADD 
CONSTRAINT pk_CTHD PRIMARY KEY ( SOHD ,MASP )
GO 

ALTER TABLE HOADON ADD FOREIGN KEY ( MAKH ) REFERENCES KHACHHANG ( MAKH)

ALTER TABLE HOADON ADD FOREIGN KEY ( MANV ) REFERENCES NHANVIEN ( MANV)

ALTER TABLE CTHD ADD FOREIGN KEY ( MASP ) REFERENCES SANPHAM ( MASP)

ALTER TABLE CTHD ADD FOREIGN KEY ( SOHD ) REFERENCES HOADON ( SOHD)












