create database QLGV
go
use QLGV
CREATE TABLE HOCVIEN(
MAHV CHAR (5) PRIMARY KEY,
HO VARCHAR (40) not null,
TEN VARCHAR (10) not null,
NGSINH SMALLDATETIME ,
GIOITINH varchar (3) not null,
NOISINH VARCHAR (40) NOT NULL ,
MALOP CHAR (3) NOT NULL 
)
GO

CREATE TABLE LOP(
MALOP CHAR (3) PRIMARY KEY,
TENLOP VARCHAR (40) not null,
TRGLOP CHAR (5) not null,
SISO TINYINT NOT NULL  ,
MAGVCN CHAR (4) not null
)
GO

CREATE TABLE KHOA(
MAKHOA VARCHAR (4) PRIMARY KEY,
TENKHOA VARCHAR (40) not null,
NGTLAP SMALLDATETIME not null,
TRGKHOA CHAR (4) NOT NULL 
)
GO

CREATE TABLE MONHOC(
MAMH VARCHAR (10) PRIMARY KEY,
TENMH VARCHAR (40) not null,
TCLT TINYINT not null,
TCTH TINYINT NOT NULL  ,
MAKHOA VARCHAR (4) not null
)
GO

CREATE TABLE DIEUKIEN(
MAMH VARCHAR (10) NOT NULL,
MAMH_TRUOC VARCHAR (10) not null
)
GO

CREATE TABLE GIAOVIEN(
MAGV CHAR (4) PRIMARY KEY,
HOTEN VARCHAR (40) not null,
HOCVI VARCHAR (10) not null,
HOCHAM CHAR (10) NOT NULL  ,
GIOITINH VARCHAR (3) not null,
NGSINH SMALLDATETIME not null,
NGVL SMALLDATETIME not null,
HESO NUMERIC (4,2) not null,
MUCLUONG MONEY not null,
MAKHOA VARCHAR (4) not null
)
GO

CREATE TABLE GIANGDAY(
MALOP CHAR (3) NOT NULL,
MAMH VARCHAR (10) not null,
MAGV CHAR (4) not null,
HOCKI TINYINT NOT NULL  ,
NAM SMALLINT not null,
TUNGAY SMALLDATETIME NOT NULL  ,
DENNGAY SMALLDATETIME NOT NULL 
)
GO

CREATE TABLE KETQUATHI(
MAHV CHAR (5) NOT NULL,
MAMH VARCHAR (10) not null,
LANTHI TINYINT not null,
NGTHI SMALLDATETIME NOT NULL  ,
DIEM NUMERIC(4,2) not null,
KQUA VARCHAR (10) NOT NULL  
)
GO

--Tạo khóa chính
ALTER TABLE KETQUATHI
ADD
CONSTRAINT pk_KETQUATHI PRIMARY KEY (MAHV, MAMH, LANTHI) 
GO

ALTER TABLE GIANGDAY
ADD
CONSTRAINT pk_GIANGDAY PRIMARY KEY (MALOP, MAMH) 
GO

ALTER TABLE DIEUKIEN
ADD
CONSTRAINT pk_DIEUKIEN PRIMARY KEY (MAMH, MAMH_TRUOC) 
GO

--Tạo khóa ngoại
ALTER TABLE LOP ADD CONSTRAINT fk_TRGLOP FOREIGN KEY(TRGLOP) REFERENCES HOCVIEN(MAHV)
GO

ALTER TABLE LOP ADD CONSTRAINT fk_MAGVCN FOREIGN KEY(MAGVCN) REFERENCES GIAOVIEN(MAGV)
GO

ALTER TABLE GIANGDAY ADD CONSTRAINT fk_MAMH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
GO

ALTER TABLE KETQUATHI ADD CONSTRAINT fk_MAHV FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV)
GO

ALTER TABLE DIEUKIEN ADD CONSTRAINT fk_MAMH_TRUOC FOREIGN KEY(MAMH_TRUOC) REFERENCES MONHOC(MAMH)
GO

ALTER TABLE MONHOC ADD CONSTRAINT fk_MAKHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)
GO

ALTER TABLE HOCVIEN ADD CONSTRAINT fk_MAGV FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV)
GO

ALTER TABLE KHOA ADD CONSTRAINT fk_TRGKHOA FOREIGN KEY(TRGKHOA) REFERENCES GIAOVIEN(MAGV)
GO




